<script src="/assets/js/jquery-3.1.1.min.js"></script>
<script src="/assets/js/bootstrap-3.3.7.min.js"></script>

<!-- JS -->
<script src="{{ site.url }}/assets/js/jquery-1.12.0.min.js"></script>
<script src="{{ site.url }}/assets/js/jquery.dlmenu.min.js"></script>
<script src="{{ site.url }}/assets/js/jquery.goup.min.js"></script>
<script src="{{ site.url }}/assets/js/jquery.magnific-popup.min.js"></script>
<script src="{{ site.url }}/assets/js/jquery.fitvid.min.js"></script>
<script src="{{ site.url }}/assets/js/scripts.js"></script>