<head>
  <meta charset="UTF-8">
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>WYX</title>

  <link rel="stylesheet" href="{{ site.url }}/assets/css/main.css">
  <link rel="stylesheet" href="/assets/css/animate.css">
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>