<head>
  <meta charset="UTF-8">
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>WYX</title>

  <!-- CSS -->
  <link rel="stylesheet" href="/assets/css/main.css">
  <link rel="stylesheet" href="/assets/css/animate.css">
  <!-- Favicons -->
  <link rel="shortcut icon" href="/favicon.ico" type="/favicon.ico">
  <!-- Background Image -->
  <style type="text/css"> body {background-image:url(/assets/img/BlurredBackground.jpg);  background-repeat: no-repeat; background-size: cover;}
  </style>
  <!-- JS -->
  <script src="{{ site.url }}/assets/js/modernizr-3.3.1.custom.min.js"></script>
  {% include hotjar.inc %}
  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
  
  <!-- Post Feature Image -->
    {% if page.feature %}
    <style type="text/css">.feature {background-image:url({{ page.feature }});}</style>
    {% endif %}
  
<!-- Hotjar Tracking Code for yixuanwang.github.io -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:576821,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</head>
