<!--<div class="left-container">
  
  <div class="details">
  <img class="logo" src="/assets/images/wangyixuan.png">
    <br>
	<h1>blabla</h1>
	<p>alkfshdfkjhe askudfh asfdkh afsdhk</p>
	<br>
  <div class="list-group hidden-xs">
    <a class="list-group-item" href="#"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp; Home</a>
    <a class="list-group-item" href="#"><i class="fa fa-book fa-fw" aria-hidden="true"></i>&nbsp; Library</a>
    <a class="list-group-item" href="#"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i>&nbsp; Applications</a>
    <a class="list-group-item" href="#"><i class="fa fa-cog fa-fw" aria-hidden="true"></i>&nbsp; Settings</a>
  </div>
  </div>
</div>
-->